Mu2e/TrackerHardwareDB

- panel-qc-viewer/public/javascripts/main.js
With this change one can do
```
PORT=XXXX npm start
````
to run on a different port
> Allow for user-defined port numbers

- panel-qc-viewer/app.js
- panel-qc-viewer/package.json
- panel-qc-viewer/public/javascripts/hv_data.js
- panel-qc-viewer/public/javascripts/main.js
- panel-qc-viewer/routes/getHVData.js
- panel-qc-viewer/routes/hv_data.js
- panel-qc-viewer/views/hv_data.pug
- panel-qc-viewer/views/index.pug
In this PR:
- new HV data page to plot the raw HV data
- use max_erf_fit plots from database instead of using dummy data
- tweak binning of straw status plot so that histogram bars are centered on the channel number
> Adding HV data and max_erf_fit plots

- sql/create_planes_table.sql
A script to create a plane table.
> create plane table

- panel-qc-viewer/app.js
- panel-qc-viewer/db/findPanels.js
- panel-qc-viewer/db/getPlane.js
- panel-qc-viewer/public/javascripts/fnal_plane_db.js
- panel-qc-viewer/public/javascripts/hv_data.js
- panel-qc-viewer/public/javascripts/panel_qc_plot.js
- panel-qc-viewer/public/javascripts/plane_qc.js
- panel-qc-viewer/views/fnal_plane_db.pug
- panel-qc-viewer/views/hv_data.pug
- panel-qc-viewer/views/layout.pug
- panel-qc-viewer/views/plane_qc.pug
- python/create_insert_maxerf_risetime.py
In this PR:
- update plane QC page, to read the actual panel numbers form the qc.planes database
- add HV data page with the plots that Minh produces
- add a python script that takes the HV data for a specific panel and creates SQL insert commands so they can be imported into the database
- update the panel QC plot to read rise time data from the database
> More updates

- python/create_update_maxerf_risetime.py
- sql/create_panels_table.sql
- added create and update privilieges for mu2e_tracker_writer role
- fixed bug in create_update_maxerf_risetime.py script
> Two updates

- panel-qc-viewer/public/javascripts/all_panel_qc.js
- panel-qc-viewer/public/javascripts/panel_qc_plot.js
Adding pages etc. for the ear board tests and updating some axis limits
> Plot updates

- panel-qc-viewer/db/allPanels.js
- panel-qc-viewer/db/allPlanes.js
- panel-qc-viewer/db/getPanel.js
- panel-qc-viewer/db/getPlane.js
- panel-qc-viewer/db/getRawHVData.js
- panel-qc-viewer/public/javascripts/all_panel_qc.js
- panel-qc-viewer/public/javascripts/panel_qc_plot.js
- panel-qc-viewer/public/javascripts/plane_qc.js
- python/create_imported_fnal_planesdb.py
- python/create_insert_new_panels.py
- python/create_insert_new_planes.py
- python/create_update_maxerf_risetime.py
- python/create_update_qc_panels_table.py
- python/create_update_qc_planes_table.py
- python/extract_updates_from_imported_fnal_planesdb.py
- update port numbers
- various plot improvements
- new scripts for extracting information for qc.panels and qc.planes from imported.fnal_planes
> Various updates

- panel-qc-viewer/public/javascripts/all_panel_qc.js
- panel-qc-viewer/views/all_panel_qc.pug
- panel-qc-viewer/views/layout.pug
Added an issues vs plane number plot, and also swapped plane and panel plots around
> Updated QC summary page

- panel-qc-viewer/public/javascripts/panel_qc_plot.js
- sql/create_repairs_tables.sql
Here I add the straw numbers to the qc text summary
> Adding straw numbers to qc summary

- panel-qc-viewer/public/javascripts/hv_data.js
- panel-qc-viewer/public/javascripts/panel_qc.js
- panel-qc-viewer/public/javascripts/plane_qc.js
- panel-qc-viewer/public/javascripts/repairs_table.js
- panel-qc-viewer/views/hv_data.pug
- python/create_update_maxerf_risetime.py
Adds ability to look back at previous max_erf and rise_time data. These columns are now included in the repairs table when they change
> Next update

- panel-qc-viewer/public/javascripts/hv_data.js
Add repair comment to the legend. Handle situtations where we have already added Fe55 data, or when we add Fe55 data later
> Update historical Fe55 data plot

- panel-qc-viewer/public/javascripts/single_channel_issues.js
- python/create_update_qc_panels_table.py
- sql/create_panels_table.sql
to qc.panels: loose_preamp_connections and low_anode_cathode_resistances for the results of the LV/HV tests after electronics installation
> Add two new columns

- python/create_update_qc_planes_table_old.py
- python/extract_updates_from_imported_fnal_planesdb.py
Panel QC team now update missing straws, high current wires etc. directly. Also use old version of update_qc_planes script
> Update extraction script

- panel-qc-viewer/public/javascripts/panel_qc_plot.js
- python/create_update_qc_panels_table.py
- sql/create_panels_table.sql
updated database table, python scripts, viewer, and wiki
> Added survey_hole_problem flags to qc.panels

- python/create_insert_new_panels.py
- python/create_insert_new_planes.py
- python/create_insert_panel_hv_data_files.py
- python/create_insert_panel_measurements.py
- python/create_insert_plane_measurements.py
- python/create_update_maxerf_risetime.py
- python/create_update_qc_panels_table.py
- python/create_update_qc_planes_table.py
- python/create_update_qc_planes_table_old.py
- setup.sh
The database was moved to ifdb11
> Updates for new machine

- python/create_insert_panel_hv_data_files.py
If it does, add a counter to the filename
> Add check to make sure that tarball filename doesn't already exist

- panel-qc-viewer/public/javascripts/all_panel_qc.js
- panel-qc-viewer/public/javascripts/single_channel_issues.js
- python/create_update_qc_panels_table.py
- sql/create_panels_table.sql
Also setting its default visibility to 'legendonly' since it is not an issue we want to count
> Adding kapton_dots column

- README.md
- panel-qc-viewer/public/javascripts/all_panel_qc.js
- panel-qc-viewer/public/javascripts/panel_qc.js
- panel-qc-viewer/public/javascripts/panel_qc_plot.js
- panel-qc-viewer/public/javascripts/plane_qc.js
- panel-qc-viewer/views/all_panel_qc.pug
- panel-qc-viewer/views/panel_qc.pug
- panel-qc-viewer/views/plane_qc.pug
* nicer summary table for panel-level issues
* full table of all panels with totals
* added section to Panel page to show FNAL Planes DB info
> Updates to QC viewer

- python/create_imported_ATD_spreadsheet.py
- look for "Disconnected" in "Status after CuClip..." spreadsheet column
- record more unspecified problems (either empty or "-" and have a channel number in spreadsheet)
- skip channels that are non-numeric strings (like "all" or "general")
> Updates to ATD script

- python/create_imported_ATD_spreadsheet.py
to write python commands when the user makes changes to the update
> Update ATD script
